val TEST_EMAIL = "test@superd.net"
val TEST_PASSWORD = "pass123"
val TEST_FIRSTNAME = "firstname"
val TEST_LASTNAME = "lastname"
val TEST_SCHOOL_REFERENCE = "SiretDuPlessis"
val TEST_SCHOOL_NAME = "plessis"
val TEST_SESSIONID = "sessionId349jklsgio"
